name: Documentation
on:
  push:
    branches:
      - development

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip install sphinx furo myst-parser sphinx-toolbox sphinx-design 
          pip install pandas pyterrier ir_datasets
          cd docs
          # sphinx-apidoc -o . ../python-client/tira
          make doctest
          make html
          touch _build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
          target-folder: nightly
